CREATE OR REPLACE VIEW MART.V_DAILY_FLOWS AS
SELECT
  D.DATE_KEY,
  D.YEAR,
  D.MONTH,
  SUM(F.DEBIT_AMOUNT)  AS TOTAL_DEBITS,
  SUM(F.CREDIT_AMOUNT) AS TOTAL_CREDITS,
  SUM(F.CREDIT_AMOUNT) - SUM(F.DEBIT_AMOUNT) AS NET_FLOW
FROM CORE.FACT_TRANSACTIONS F
JOIN CORE.DIM_DATE D ON D.DATE_KEY = F.POSTING_DATE_KEY
GROUP BY D.DATE_KEY, D.YEAR, D.MONTH;