create or replace view CU_DB.MART.V_ACH_RETURN_RATE_BY_STATE(
	STATE,
	TOTAL_TXNS,
	RETURN_TXNS,
	RETURN_RATE_PCT
) as
SELECT
  M.STATE,
  COUNT(*) AS TOTAL_TXNS,
  SUM(IFF(F.ACH_RETURN_CODE IS NOT NULL, 1, 0)) AS RETURN_TXNS,
  ROUND(
    100.0 * SUM(IFF(F.ACH_RETURN_CODE IS NOT NULL, 1, 0)) / COUNT(*),
    2
  ) AS RETURN_RATE_PCT
FROM CORE.FACT_TRANSACTIONS F
JOIN CORE.DIM_MEMBER M ON M.MEMBER_ID = F.MEMBER_ID
GROUP BY M.STATE;