create or replace view CU_DB.MART.V_CHANNEL_MIX(
	CHANNEL,
	TXN_COUNT,
	TOTAL_AMOUNT,
	PCT_OF_TRANSACTIONS
) as
SELECT
  F.CHANNEL,
  COUNT(*)                  AS TXN_COUNT,
  SUM(F.DEBIT_AMOUNT + F.CREDIT_AMOUNT) AS TOTAL_AMOUNT,
  ROUND(
    100.0 * COUNT(*) / SUM(COUNT(*)) OVER(), 
    2
  ) AS PCT_OF_TRANSACTIONS
FROM CORE.FACT_TRANSACTIONS F
GROUP BY F.CHANNEL;