create or replace view CU_DB.MART.V_HOLD_RATE_BY_BRANCH(
	BRANCH_CODE,
	TOTAL_TXNS,
	HOLD_TXNS,
	HOLD_RATE_PCT
) as
SELECT
  A.BRANCH_CODE,
  COUNT(*) AS TOTAL_TXNS,
  SUM(IFF(F.HOLD_FLAG = 1, 1, 0)) AS HOLD_TXNS,
  ROUND(
    100.0 * SUM(IFF(F.HOLD_FLAG = 1, 1, 0)) / COUNT(*),
    2
  ) AS HOLD_RATE_PCT
FROM CORE.FACT_TRANSACTIONS F
JOIN CORE.DIM_ACCOUNT A ON A.ACCOUNT_ID = F.ACCOUNT_ID
GROUP BY A.BRANCH_CODE;