create or replace TABLE CU_DB.CORE.DIM_DATE (
	DATE_KEY TIMESTAMP_NTZ(9),
	YEAR NUMBER(4,0),
	QUARTER NUMBER(2,0),
	MONTH NUMBER(2,0),
	DAY NUMBER(2,0),
	DAY_OF_WEEK_ISO NUMBER(2,0),
	IS_WEEKEND VARCHAR(1)
);