INSERT INTO CORE.DIM_ACCOUNT
(ACCOUNT_ID, MEMBER_ID, ACCOUNT_TYPE, OPEN_DATE, STATUS, BRANCH_CODE)
SELECT
  ACCOUNT_ID,
  MEMBER_ID,
  ACCOUNT_TYPE,
  OPEN_DATE,
  STATUS,
  BRANCH_CODE
FROM STG.ACCOUNTS_STG;