INSERT INTO CORE.DIM_DATE
(DATE_KEY, YEAR, QUARTER, MONTH, DAY, DAY_OF_WEEK_ISO, IS_WEEKEND)
WITH dates AS (
  SELECT
    DATEADD(DAY, SEQ4(), '2020-01-01') AS FULL_DATE
  FROM TABLE(GENERATOR(ROWCOUNT => 2000)) 
)
SELECT
  FULL_DATE                         AS DATE_KEY, -- surrogate key
  YEAR(FULL_DATE)                   AS YEAR,
  QUARTER(FULL_DATE)                AS QUARTER,
  MONTH(FULL_DATE)                  AS MONTH,
  DAY(FULL_DATE)                    AS DAY,
  DAYOFWEEKISO(FULL_DATE)           AS DAY_OF_WEEK_ISO,
  CASE WHEN DAYOFWEEKISO(FULL_DATE) IN (6,7) THEN 'Y' ELSE 'N' END AS IS_WEEKEND
FROM dates;