INSERT INTO CORE.DIM_MEMBER
(MEMBER_ID, JOIN_DATE, DOB, STATE, RISK_SCORE, KYC_STATUS, PEP_FLAG)
SELECT
  MEMBER_ID,
  JOIN_DATE,
  DOB,
  STATE,
  RISK_SCORE,
  KYC_STATUS,
  PEP_FLAG
FROM STG.MEMBERS_STG;