INSERT INTO CORE.FACT_TRANSACTIONS
(TXN_ID, ACCOUNT_ID, MEMBER_ID, POSTING_DATE, POSTING_DATE_KEY, CHANNEL, MERCHANT_CATEGORY, AMOUNT, DEBIT_AMOUNT, CREDIT_AMOUNT, HOLD_FLAG, ACH_RETURN_CODE)
SELECT
  T.TXN_ID,
  T.ACCOUNT_ID,
  A.MEMBER_ID,
  T.POSTING_DATE,
  D.DATE_KEY                      AS POSTING_DATE_KEY,
  T.CHANNEL,
  T.MERCHANT_CATEGORY,
  T.AMOUNT,

  -- Derived amounts for easier KPIs
  CASE WHEN T.IS_DEBIT = 1 THEN ABS(T.AMOUNT) ELSE 0 END AS DEBIT_AMOUNT,
  CASE WHEN T.IS_DEBIT = 0 THEN T.AMOUNT ELSE 0 END       AS CREDIT_AMOUNT,
  T.HOLD_FLAG,
  T.ACH_RETURN_CODE
FROM STG.TRANSACTIONS_STG T
JOIN CORE.DIM_ACCOUNT A
  ON A.ACCOUNT_ID = T.ACCOUNT_ID
JOIN CORE.DIM_DATE D
  ON D.DATE_KEY = T.POSTING_DATE;